/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarPicker: typeof import('./src/components/Profile/AvatarPicker.vue')['default']
    CategoriesField: typeof import('./src/components/Images/Fields/CategoriesField.vue')['default']
    CategoryChips: typeof import('./src/components/Images/Fields/Category/CategoryChips.vue')['default']
    CategoryCreateDialog: typeof import('./src/components/Categories/CategoryCreateDialog.vue')['default']
    CategoryDialog: typeof import('./src/components/Categories/CategoryDialog.vue')['default']
    CategoryEditDialog: typeof import('./src/components/Categories/CategoryEditDialog.vue')['default']
    CategoryNameFields: typeof import('./src/components/Categories/CategoryNameFields.vue')['default']
    CategoryPicker: typeof import('./src/components/Images/Fields/Category/CategoryPicker.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DescriptionField: typeof import('./src/components/Images/Fields/DescriptionField.vue')['default']
    FormDialog: typeof import('./src/components/FormDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageCreateDialog: typeof import('./src/components/Images/ImageCreateDialog.vue')['default']
    ImageDetailDialog: typeof import('./src/components/Images/ImageDetailDialog.vue')['default']
    ImageDialog: typeof import('./src/components/Images/ImageDialog.vue')['default']
    ImagePicker: typeof import('./src/components/Images/Fields/ImagePicker.vue')['default']
    ImageStage: typeof import('./src/components/Images/Fields/ImageStage.vue')['default']
    MemberPicker: typeof import('./src/components/Teams/MemberPicker.vue')['default']
    MemberRows: typeof import('./src/components/Teams/MemberRows.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamCreateDialog: typeof import('./src/components/Teams/TeamCreateDialog.vue')['default']
    TeamEditDialog: typeof import('./src/components/Teams/TeamEditDialog.vue')['default']
    TeamFields: typeof import('./src/components/Teams/TeamFields.vue')['default']
    TeamMembersDialog: typeof import('./src/components/Teams/TeamMembersDialog.vue')['default']
    TheAppBar: typeof import('./src/components/TheAppBar.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
    TheProfileMenu: typeof import('./src/components/TheProfileMenu.vue')['default']
    TimestampFields: typeof import('./src/components/TimestampFields.vue')['default']
    TitleField: typeof import('./src/components/Images/Fields/TitleField.vue')['default']
    UserCreateDialog: typeof import('./src/components/Users/UserCreateDialog.vue')['default']
    UserEditDialog: typeof import('./src/components/Users/UserEditDialog.vue')['default']
    UserFields: typeof import('./src/components/Users/UserFields.vue')['default']
  }
}
